name: Spring Boot => Build only

on:
  push:
    branches:
      - main

jobs:

  Back-CI:
    name: Spring Boot CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'back'

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer Java 11 pour le projet Spring Boot
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Build avec Maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      
      # 4. Exécuter les tests et générer les rapports Jacoco
      - name: Run tests with Maven
        run: mvn test jacoco:report

      # 5. Télécharger le rapport de couverture Jacoco en tant qu'artefact
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: back/target/site/jacoco