name: Spring Boot => Build, Test, SonarCloud, Docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  Back-CI:
    name: Spring Boot CI/CD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'back'

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # 2. Configurer Java 17 pour le projet Spring Boot
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 5. Compile avec Maven
      - name: Compile with Maven
        run: mvn compile

      # 6. Tests avec Maven et génération du rapport JaCoCo
      - name: Tests with Maven
        run: mvn test jacoco:report

      # 7. Construction du package avec Maven sans exécuter les tests
      - name: Build with Maven
        run: mvn package -DskipTests=true

      # 8. Télécharger le rapport de couverture JaCoCo en tant qu'artefact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco

      # 9. Analyse du code avec SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=guillaumebeysson_bob-app
