name: Spring Boot => Build, Test, SonarCloud, Docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  Back-CI:
    name: Spring Boot CI/CD
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'back'

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # 2. Configurer Java 17 pour le projet Spring Boot
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Compile avec Maven
      - name: Compile with Maven
        run: mvn compile

      # 4. Tests avec Maven et génération du rapport JaCoCo
      - name: Tests with Maven
        run: mvn test jacoco:report 
      
      # 5. Build Spring Boot JAR
      - name: Build Spring Boot JAR
        run: |
          mvn package -DskipTests

      # 6. Télécharger le rapport de couverture JaCoCo en tant qu'artefact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco

      # 7. Analyse du code avec SonarCloud
      - name: Analyze code with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN_BACKEND }} 
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=guillaumebeysson_bob-app-backend \
          -Dsonar.organization=guillaumebeysson  \
          -Dsonar.projectName=bob-app-backend \
          -Dsonar.sources=src/main/java \
          -Dsonar.tests=src/test/java \
          -Dsonar.host.url=https://sonarcloud.io \

      # 8. Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # 9. Build et push l'image Docker sur Docker Hub
      - name: Build and push Docker image (back)
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest