name: Angular => Build only

on:
  push:
    branches:
      - main

jobs:

  Frontend-CI:
    name: Angular CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'front'

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Exécuter les tests avec Karma et générer un rapport de couverture
      - name: Run tests with Karma in CI mode
        run: |
          CI=true npm run test -- --browsers=ChromeHeadless --code-coverage --watch=false

      # 5. Télécharger le rapport de couverture en tant qu'artefact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: front/coverage/bobapp

      # 6. Build du projet Angular
      - name: Build Angular app
        run: npm run build

